// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type App struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Query struct {
}
